comment:
    type: gitalk
    client_id: b06b0ae7fc48f259d968
    client_secret:  7f86a4d83e6cb65bf41444ccfda579489416c448
    repo: moelife-comment
    owner: moelife-coder
    admin:
        - moelife-coder
    per_page: 20                    # 可选填
    distraction_free_mode: false    # 可选填
    pager_direction: last           # 可选填
    create_issue_manually: false    # 可选填
    proxy:                          # 可选填
    flip_move_options:              # 可选填
    enable_hotkey: true             # 可选填
    language: zh-CN                 # 可选填
